# Generated by Django 5.1.4 on 2025-01-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='food_type',
            new_name='country_food',
        ),
    ]
