# Generated by Django 5.1.3 on 2025-01-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_info', models.TextField(verbose_name='재료 정보')),
                ('language_info', models.TextField(verbose_name='언어 정보')),
            ],
        ),
    ]
