# Generated by Django 5.1.3 on 2025-01-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredients_info',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='language_info',
            new_name='language',
        ),
    ]
