# Generated by Django 5.1.4 on 2025-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('food_time', models.CharField(max_length=15, verbose_name='식사 시간')),
                ('food_details', models.TextField(verbose_name='음식 정보')),
                ('is_on_diet', models.BooleanField(default=False, verbose_name='다이어트 중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
        ),
    ]
