# Generated by Django 5.1.4 on 2025-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calories',
            name='food_time',
            field=models.CharField(max_length=150, verbose_name='식사 시간'),
        ),
    ]
