# Generated by Django 5.1.4 on 2025-01-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_alter_calories_food_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='calories',
            name='breakfast_time',
            field=models.TextField(blank=True, null=True, verbose_name='아침 정보'),
        ),
        migrations.AddField(
            model_name='calories',
            name='lunch_time',
            field=models.TextField(blank=True, null=True, verbose_name='점심 정보'),
        ),
    ]
