<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-20 20:40
=======
# Generated by Django 5.1.4 on 2024-12-31 10:59
>>>>>>> JSH

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그들',
            },
=======
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
>>>>>>> JSH
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('양식', '양식'), ('일식', '일식'), ('한식', '한식'), ('중식', '중식')], default='양식', max_length=10)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_recipes', to='accounts.customuser')),
                ('tags', models.ManyToManyField(blank=True, related_name='food_recipes', to='food.tag')),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='accounts.customuser')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='food.recipe')),
            ],
            options={
                'verbose_name': '즐겨찾기 레시피',
                'verbose_name_plural': '즐겨찾기 레시피들',
                'unique_together': {('user', 'recipe')},
            },
=======
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('Ingredient', models.ManyToManyField(to='food.ingredient')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
>>>>>>> JSH
        ),
    ]
